=== dougdonohoe/ddphotos-app/code/engine/src/main/resources/config/xml-schema/appdef.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.donohoedigital.com"
            xmlns="http://www.donohoedigital.com"
            xmlns:dd="http://www.donohoedigital.com"
            elementFormDefault="qualified">

    <xsd:include schemaLocation="classpath:config/xml-schema/data-elements.xsd"/>

<!-- ********************************** -->
<!-- DEFINES TYPES                      -->
<!-- ********************************** -->

	<xsd:complexType name="paramlist">
    	<xsd:sequence>
	    	<xsd:element name="strvalue" type="string" minOccurs="0" maxOccurs="unbounded"/>
	    	<xsd:element name="boolvalue" type="boolean" minOccurs="0" maxOccurs="unbounded"/>
	    	<xsd:element name="intvalue" type="integer" minOccurs="0" maxOccurs="unbounded"/>
	    	<xsd:element name="dblvalue" type="double" minOccurs="0" maxOccurs="unbounded"/>
    	</xsd:sequence>
		<xsd:attribute name="name" type="basicname" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="param">
		<xsd:attribute name="name" type="basicname" use="required"/>
		<xsd:attribute name="strvalue" type="string" use="optional"/>
		<xsd:attribute name="boolvalue" type="boolean" use="optional"/>
		<xsd:attribute name="intvalue" type="integer" use="optional"/>
		<xsd:attribute name="dblvalue" type="double" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="phase">
    	<xsd:sequence>
	    	<xsd:element name="param" type="param" minOccurs="0" maxOccurs="unbounded"/>
	    	<xsd:element name="paramlist" type="paramlist" minOccurs="0" maxOccurs="unbounded"/>
    	</xsd:sequence>
		<xsd:attribute name="name" type="basicname" use="required"/>
		<xsd:attribute name="class" type="classname" use="optional"/>
		<xsd:attribute name="extends" type="basicname" use="optional"/>
		<xsd:attribute name="cache" type="boolean" use="optional"/>
		<xsd:attribute name="history" type="boolean" use="optional"/>
		<xsd:attribute name="transient" type="boolean" use="optional"/>
		<xsd:attribute name="window" type="basicname" use="optional"/>
	</xsd:complexType>

<!-- ********************************** -->
<!-- OBJECTS DEFINITION (FOR XML DOCS)  -->
<!-- ********************************** -->

    <xsd:element name="APPDEF">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element name="startphase" type="basicname" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="phase" type="phase" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>

		<!-- define phase name is a key and must be unique -->
		<xsd:key name="PHASE-KEY">
			<xsd:selector xpath="dd:phase"/>
			<xsd:field xpath="@name"/>
		</xsd:key> 

		<!-- define startphase name must ref valid phase -->
		<xsd:keyref name="START-PHASE-REF" refer="PHASE-KEY">
            <xsd:selector xpath="dd:APPDEF"/>
            <xsd:field xpath="startphase"/>
        </xsd:keyref>

		<!-- define extends name must ref valid phase -->
		<xsd:keyref name="EXTENDS-PHASE-REF" refer="PHASE-KEY">
            <xsd:selector xpath="dd:phase"/>
            <xsd:field xpath="extends"/>
        </xsd:keyref>

    </xsd:element>
</xsd:schema>

=== dougdonohoe/ddphotos-app/code/photos/src/main/resources/config/ddphotos/appdef.xml
<?xml version="1.0"?>
<APPDEF xmlns="http://www.donohoedigital.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.donohoedigital.com ../../../../../../engine/src/main/resources/config/xml-schema/appdef.xsd">

    <!--              -->
    <!-- START PHASE  -->
    <!--              -->

    <startphase>StartMenu</startphase>

    <!--         -->
    <!-- PHASES  -->
    <!--         -->

    <phase name="StartMenu" class="com.donohoedigital.ddphotos.PhotosBasePhase" history="true"/>

    <phase name="Help" class="com.donohoedigital.app.engine.Help" history="true" window="help" cache="true">
        <param name="window-title" strvalue="msg.windowtitle.help"/>
        <param name="window-width" intvalue="940"/>
        <param name="window-height" intvalue="700"/>
        <param name="window-multi" boolvalue="false"/>
        <param name="window-resize" boolvalue="true"/>
        <param name="style" strvalue="Help"/>
        <param name="bevel-style" strvalue=""/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-style" strvalue="Help"/>
        <param name="dialog-window-close-activates-button" strvalue="close"/>
        <param name="default-button" strvalue="close"/>
        <paramlist name="buttons">
            <strvalue>close</strvalue>
        </paramlist>
    </phase>

    <phase name="Support" class="com.donohoedigital.app.engine.Support" history="true" window="support" cache="true">
        <param name="window-title" strvalue="msg.windowtitle.support"/>
        <param name="window-width" intvalue="1600"/>
        <param name="window-height" intvalue="800"/>
        <param name="window-multi" boolvalue="false"/>
        <param name="window-resize" boolvalue="true"/>
        <param name="style" strvalue="Support"/>
        <param name="bevel-style" strvalue=""/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-style" strvalue="Support"/>
        <param name="dialog-window-close-activates-button" strvalue="close"/>
        <param name="default-button" strvalue="close"/>
        <paramlist name="buttons">
            <strvalue>close</strvalue>
        </paramlist>
    </phase>

    <phase name="SiteDialog" class="com.donohoedigital.ddphotos.SiteDialog" transient="true">
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.SiteDialog"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-window-close-activates-button" strvalue="cancel"/>
        <param name="default-button" strvalue="save"/>
        <paramlist name="buttons">
            <strvalue>cancel</strvalue>
            <strvalue>save</strvalue>
        </paramlist>
    </phase>

    <phase name="AlbumDialog" class="com.donohoedigital.ddphotos.AlbumDialog" transient="true">
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.AddAlbumDialog"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-window-close-activates-button" strvalue="cancel"/>
        <param name="default-button" strvalue="save"/>
        <paramlist name="buttons">
            <strvalue>cancel</strvalue>
            <strvalue>save</strvalue>
        </paramlist>
    </phase>

    <phase name="BaseDialog" class="com.donohoedigital.ddphotos.BaseDialog" transient="true">
        <param name="style" strvalue="OptionsDialog"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.AddBaseDialog"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-window-close-activates-button" strvalue="cancel"/>
        <param name="default-button" strvalue="save"/>
        <paramlist name="buttons">
            <strvalue>cancel</strvalue>
            <strvalue>save</strvalue>
        </paramlist>
    </phase>

    <phase name="DisplayInfoMessage" class="com.donohoedigital.app.engine.DisplayMessage" transient="true">
        <param name="style" strvalue="DisplayMessage"/>
        <param name="dialog-style" strvalue="DisplayMessage"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.displayInfoMessage"/>
        <param name="dialog-minwidth" intvalue="350"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-window-close-activates-button" strvalue="okay"/>
        <param name="default-button" strvalue="okay"/>
        <paramlist name="buttons">
            <strvalue>okay</strvalue>
        </paramlist>
    </phase>

    <phase name="DisplayWarning" class="com.donohoedigital.app.engine.DisplayMessage" transient="true">
        <param name="style" strvalue="DisplayMessage"/>
        <param name="dialog-style" strvalue="DisplayMessage"/>
        <param name="dialog-type" strvalue="warn"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.displayWarning"/>
        <param name="dialog-minwidth" intvalue="350"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-window-close-activates-button" strvalue="okay"/>
        <param name="default-button" strvalue="okay"/>
        <paramlist name="buttons">
            <strvalue>okay</strvalue>
        </paramlist>
    </phase>

    <phase name="DisplayError" class="com.donohoedigital.app.engine.DisplayMessage" transient="true">
        <param name="style" strvalue="DisplayMessage"/>
        <param name="dialog-style" strvalue="DisplayMessage"/>
        <param name="dialog-type" strvalue="error"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.displayError"/>
        <param name="dialog-minwidth" intvalue="350"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-window-close-activates-button" strvalue="okay"/>
        <param name="default-button" strvalue="okay"/>
        <paramlist name="buttons">
            <strvalue>okay</strvalue>
        </paramlist>
    </phase>

    <phase name="DisplayConfirmation" class="com.donohoedigital.app.engine.DisplayMessage" transient="true">
        <param name="style" strvalue="DisplayMessage"/>
        <param name="dialog-style" strvalue="DisplayMessage"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.displayConfirmation"/>
        <param name="dialog-minwidth" intvalue="350"/>
        <param name="dialog-modal" boolvalue="true"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-window-close-activates-button" strvalue="no"/>
        <param name="default-button" strvalue="yes"/>
        <param name="dialog-no-show-checkbox-name" strvalue="noshowconfirmation"/>
        <paramlist name="buttons">
            <strvalue>yes</strvalue>
            <strvalue>no</strvalue>
        </paramlist>
    </phase>

    <phase name="TourWelcome" class="com.donohoedigital.app.engine.DisplayMessage" transient="true">
        <param name="style" strvalue="DisplayMessage"/>
        <param name="dialog-style" strvalue="DisplayMessage"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.tour"/>
        <param name="dialog-minwidth" intvalue="750"/>
        <param name="dialog-modal" boolvalue="false"/>
        <param name="dialog-help-name" strvalue="empty"/>
        <param name="dialog-window-close-activates-button" strvalue="tourskip"/>
        <param name="default-button" strvalue="tourstart"/>
        <param name="default-no-show-button" strvalue="tourskip"/>
        <param name="dialog-no-show-option" boolvalue="true"/>
        <param name="dialog-no-show-key" strvalue="show.tour"/>
        <param name="dialog-no-show-checkbox-name" strvalue="noshowtour"/>
        <paramlist name="buttons">
            <strvalue>tourstart</strvalue>
            <strvalue>tourskip</strvalue>
        </paramlist>
    </phase>

    <phase name="TourStep" class="com.donohoedigital.app.engine.DisplayMessage" transient="true">
        <param name="style" strvalue="DisplayMessage"/>
        <param name="dialog-style" strvalue="DisplayMessage"/>
        <param name="dialog-background-image" strvalue="dialog-background"/>
        <param name="dialog-windowtitle-image" strvalue="window-title-icon"/>
        <param name="dialog-windowtitle-prop" strvalue="msg.windowtitle.tour"/>
