=== dougdonohoe/ddphotos-app/code/common/src/main/resources/config/xml-schema/help.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.donohoedigital.com"
            xmlns="http://www.donohoedigital.com"
            elementFormDefault="qualified">

    <xsd:include schemaLocation="classpath:config/xml-schema/data-elements.xsd"/>

<!-- ********************************** -->
<!-- DEFINES TYPES                      -->
<!-- ********************************** -->

	<xsd:complexType name="help">
		<xsd:attribute name="location" type="filename" use="required"/>
		<xsd:attribute name="name" type="basicname" use="required"/>
		<xsd:attribute name="display" type="string" use="required"/>
		<xsd:attribute name="indent" type="nonNegativeInteger" default="0" use="optional"/>
	</xsd:complexType>

<!-- ********************************** -->
<!-- OBJECTS DEFINITION (FOR XML DOCS)  -->
<!-- ********************************** -->

    <xsd:element name="HELPS">
		<xsd:complexType mixed="true">
			<xsd:sequence>

				<xsd:element name="helpdir" 
						type="filename" minOccurs="1" maxOccurs="1"/>

				<xsd:element name="help" 
						type="help" minOccurs="0" maxOccurs="unbounded"/>

			</xsd:sequence>
		</xsd:complexType>
    </xsd:element>
  
</xsd:schema>

=== dougdonohoe/ddphotos-app/code/photos/src/main/resources/config/ddphotos/help.xml
<?xml version="1.0"?>
<!--
#*#*# Copyright 2003 Donohoe Digital LLC.  All rights reserved.
#*# DONOHOE DIGITAL PROPRIETARY/CONFIDENTIAL. Use is subject to license terms. 
#*#
#*# MODIFICATION OF THIS FILE IS PROHIBITED AND COULD
#*# RESULT IN SOFTWARE MALFUNCTION.
#*#
-->
<HELPS xmlns="http://www.donohoedigital.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.donohoedigital.com ../../../../../../common/src/main/resources/config/xml-schema/help.xsd">

		<helpdir>help</helpdir>

		<help name="intro"  display="Introduction" location="intro.html"/>
		<help name="deployment"  display="Deploying Your Site" location="deployment.html"/>
		<help name="wizard"  display="Wizard Instructions" location="wizard.html"/>
		<help name="whatsnew" display="What's New?" location="whatsnew.html"/>

		<help name="general"  display="General Info" location="general.html"/>
			<help name="ddigital"  display="Donohoe Digital" location="ddigital.html" indent="1"/>                	
			<help name="credits"  display="Credits &amp; Legal" location="credits.html" indent="1"/>
			<help name="license"  display="License" location="license.html" indent="1"/>

</HELPS>
