=== dougdonohoe/ddphotos-app/code/common/src/main/resources/config/xml-schema/images.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.donohoedigital.com"
            xmlns="http://www.donohoedigital.com"
            elementFormDefault="qualified">

    <xsd:include schemaLocation="classpath:config/xml-schema/data-elements.xsd"/>

<!-- ********************************** -->
<!-- DEFINES TYPES                      -->
<!-- ********************************** -->

	<xsd:complexType name="image">
		<xsd:attribute name="location" type="filename" use="required"/>
		<xsd:attribute name="name" type="basicname" use="required"/>
		<xsd:attribute name="cache" type="boolean" use="optional"/>
		<xsd:attribute name="components" type="basicname" use="optional"/>
		<xsd:attribute name="x" type="nonNegativeInteger" use="optional"/>
		<xsd:attribute name="y" type="nonNegativeInteger" use="optional"/>
	</xsd:complexType>

<!-- ********************************** -->
<!-- OBJECTS DEFINITION (FOR XML DOCS)  -->
<!-- ********************************** -->

    <xsd:element name="IMAGES">
		<xsd:complexType mixed="true">
			<xsd:sequence>

				<xsd:element name="imagedir" 
						type="filename" minOccurs="1" maxOccurs="1"/>

				<xsd:element name="image" 
						type="image" minOccurs="0" maxOccurs="unbounded"/>

			</xsd:sequence>
		</xsd:complexType>
    </xsd:element>
  
</xsd:schema>

=== dougdonohoe/ddphotos-app/code/photos/src/main/resources/config/ddphotos/images.xml
<?xml version="1.0"?>
<IMAGES xmlns="http://www.donohoedigital.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.donohoedigital.com ../../../../../../common/src/main/resources/config/xml-schema/images.xsd">

  <imagedir>images</imagedir>

  <!-- window/taskbar icons (Windows + Linux); BaseFrame loads all sizes via setIconImages() -->
  <image name="gui.icon.16" location="logo_16x16.png"/>
  <image name="gui.icon.32" location="logo_32x32.png"/>
  <image name="gui.icon.48" location="logo_48x48.png"/>
  <image name="gui.icon.64" location="logo_64x64.png"/>
  <image name="gui.icon.128" location="logo_128x128.png"/>
  <image name="gui.icon.256" location="logo_256x256.png"/>

  <image name="splash" location="splash.png" cache="false"/>
  <image name="splash-empty" location="splash.png" cache="false"/>
  <image name="window-title-icon" location="icon_20x20.png"/>
  <image name="dialog-background" location="dialog-background.png"/>

  <!-- main screen icon -->
  <image name="button.icon48.up" location="logo_48x48.png"/>
  <image name="button.icon48.over" location="logo_48x48.png"/>
  <image name="button.icon48.down" location="logo_48x48.png"/>
  <image name="button.icon48.disable" location="logo_48x48.png"/>

  <!-- help images -->
  <image name="ddlogo" location="donohoe-digital-logo.png"/>
  <image name="ddphotos-logo" location="logo_128x128.png"/>

</IMAGES>
